// let Person = {
//   name: ["Noyon", "Tamin", "Sakib"],
//   showName: function () {
//     this.name.forEach(function (element) {
//       console.log(element);
//     });
//   },
// };
// Person.showName();

// const number = {
//   numbers: [1, 2, 3, 4, 5, 6],
//   showNumber: function () {
//     this.numbers.forEach(function (num) {
//       console.log(num);
//     });
//   },
// };

// number.showNumber();

// let Person = {
//   greeting: "Hello",
//   name: ["Noyon", "Tamin", "Sakib"],
//   showName: function () {
//     this.name.forEach(function (element) {
//       console.log(this.greeting + " " + element);
//     }, this);
//   },
// };
// Person.showName();

// let Person = {
//     greeting: "Hello",
//     name: ["Noyon", "Tamin", "Sakib"],
//     showName: function () {
//       this.name.forEach((element) => {
//         console.log(this.greeting + " " + element);
//       });
//     },
//   };
//   Person.showName();
