// const obj = {
//   name: "noyon",
//   age: 21,
//   id: 1,
// };
// console.log(obj.name);

// const Objects = {
//     firstName: "Shahadat",
//     lastName: "Hosen",
//     surName: "Noyon.",
//     age: 21,
//     fullName: function(){
//         return "My Name is" + " " + this.firstName + " " + this.lastName + " " + this.surName;
//     }
// }
// console.log(Objects.fullName());

//Create an Array:

// const person = {
//     firstName: "Shahadat",
//     lastName: "Hosen",
//     surName: "Noyon.",
//     age: 21,
// }

// const myArray = Object.values(person);
// console.log(myArray);

// const person = new Object();

// person.firstName = "Shahadat Hosen";
// person.lastName = "Noyon";
// person.age = 21;
// person.id = 504;

// console.log(person);

// const user = {
//     firstName: "Shahadat",
//     lastName: "Hosen",
//     age: 21,
//     id: 504,
// }

// delete user.id;
// delete user.lastName;

// user.age = 33;
// user.age = 21;

// console.log(user);

// function Person(first, last, age, eye) {
//   this.firstName = first;
//   this.lastName = last;
//   this.age = age;
//   this.eyeColor = eye;
// }

// const user = new Person("Shahadat Hosen", "Noyon", 21, "blue");
// delete user.age;

// const hablu = new Person("Hablu", "Programmer", 22, "Black");
// delete hablu.eyeColor;

// console.log(user);
// console.log(hablu);
