// const obj = {
//   name: "noyon",
//   age: 21,
//   id: 1,
// };
// console.log(obj.name);


// const Objects = {
//     firstName: "Shahadat",
//     lastName: "Hosen",
//     surName: "Noyon.",
//     age: 21,
//     fullName: function(){
//         return "My Name is" + " " + this.firstName + " " + this.lastName + " " + this.surName;
//     }
// }
// console.log(Objects.fullName());


//Create an Array:

// const person = {
//     firstName: "Shahadat",
//     lastName: "Hosen",
//     surName: "Noyon.",
//     age: 21,
// }

// const myArray = Object.values(person);
// console.log(myArray);