// function myFunction (a, b) {
//     return a + b;
// }

// let result = myFunction(5, 9);
// console.log(result);

// const x = (a, b) => a + b;
// const y = x(2, 4);
// console.log(y);

// function myFunction(x, y) {
//   if (x === undefined) {
//     x = 0;
//   } else if (y === undefined) {
//     y = 0;
//   }
//   return x * y;
// }

// let x = myFunction(9);
// console.log(x);

// function myFunction (x, y = 5) {
//     return x * y;
// }

// let x = myFunction(5);
// console.log(x);

// const user = {
//   firstName: "Kairul",
//   lastName: "Basar",
//   fullName: function () {
//     return this.firstName + " " + this.lastName;
//   },
// };

// console.log(user.fullName());
