// function myFun () {
//     console.log("Hello World");
// }
// setTimeout(myFun, 3000);

// let x = 3;
// let y = 5;
// let z = 4;
// function myFunction() {
//   let sum = x + y + z;
//   console.log(sum);
// }
// setTimeout(myFunction, 2000);

// setTimeout(function (num1, num2) {
//     console.log(num1 + num2);
//   }, 6000, 5, 6);

// setTimeout((para1, para2)=>{
//     console.log(para1 * para2);
// }, 7000, 6, 7);

// setTimeout(function(n1, n2){
//     console.log(n1 + n2);
// }, 5000, 5, 9);

// setTimeout((sum1, sum2) => {
//     console.log(sum1 * sum2);
// }, 3000, 7, 7);


// function myFunction () {
//     let date = new Date();
//     let Time = date.getHours() + ":" + date.getMinutes() + ":" + date.getSeconds();
//     console.log(Time);
// }
// setInterval(myFunction, 1000);