// let car = ["Toyota", "Volvo", "BMW", "Royel", "Honda"];

// for (let i = 0; i <= car.length; i++) {
//   console.log(car[i]);
// }

// let car = ["Toyota", "Volvo", "BMW", "Royel", "Honda"];

// car.forEach((element) => {
//     console.log(element);
// });

// let name = ["Hablu", "Jhon", "Alex"];

// name.push("Jisan");
// name.push("Noyon");
// name.push("Kaiser");
// console.log(name);

// let name = ["Hablu", "Jhon", "Alex"];

// name.pop();
// name.pop();
// console.log(name);

// const user = [];
// user[0] = "Jhon";
// user[1] = "Hablu";
// user[2] = "Noyon";
// user[3] = "Alex";

// console.log(user.length);

// user.forEach(function (element) {
//   console.log(element.length);
// });


