// let car = ["Toyota", "Volvo", "BMW", "Royel", "Honda"];

// for (let i = 0; i <= car.length; i++) {
//   console.log(car[i]);
// }

// let car = ["Toyota", "Volvo", "BMW", "Royel", "Honda"];

// car.forEach((element) => {
//     console.log(element);
// });

// let name = ["Hablu", "Jhon", "Alex"];

// name.push("Jisan");
// name.push("Noyon");
// name.push("Kaiser");
// console.log(name);

// let name = ["Hablu", "Jhon", "Alex"];

// name.pop();
// name.pop();
// console.log(name);

// const user = [];
// user[0] = "Jhon";
// user[1] = "Hablu";
// user[2] = "Noyon";
// user[3] = "Alex";

// console.log(user.length);
// console.log(typeof user);

// user.forEach(function (element) {
//   console.log(element.length);
// });

// const myObj = {
//   name: "John",
//   age: 30,
//   cars: [
//     { name: "Ford", models: ["Fiesta", "Focus", "Mustang"] },
//     { name: "BMW", models: ["320", "X3", "X5"] },
//     { name: "Fiat", models: ["500", "Panda"] },
//   ],
// };

// console.log(myObj);
// console.log(myObj.name);
// console.log(myObj.cars);
// console.log(myObj.cars[0]);
// console.log(myObj.cars[0].name);
// console.log(myObj.cars[1].name);
// console.log(myObj.cars[2].name);
// console.log(myObj.cars[0].models);
// console.log(myObj.cars[1].models);
// console.log(myObj.cars[2].models);