// let array = ["Shahadat", "Hosen", "Noyon", "Munna", "Didar", "Kaiser"];

// for (let i = 0; i < array.length; i++) {
//   console.log(array[i]);
// }

// array.forEach(function(element){
//     console.log(element);
// })

// let number = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

// number.forEach(function (element) {
//   if (element % 2 == 0) {
//     console.log("Even");
//   } else {
//     console.log("Odd");
//   }
// });

// number.forEach(function (element) {
//   console.log(element * 3);
// });
